//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dash7
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeEntities : DbContext
    {
        public HomeEntities()
            : base("name=HomeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<Progress> Progresses { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<SIA> SIAs { get; set; }
        public virtual DbSet<TIA> TIAs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
